// All tunable numbers live here. Sourced from blueprint.md §23.
// Never hardcode tuning values in game logic - reference Balance instead.

export const Balance = {
  raid: {
    normalDuration: 75,
    tutorialDuration: 45,
    extractionOpenTime: 20,
    tutorialExtractionOpenTime: 18,
    extractionHoldTime: 5,
    extractionDecayRate: 0.85,
    draftTimes: [20, 45] as const,
    greedSteps: [
      { afterSeconds: 0, mult: 1.0 },
      { afterSeconds: 10, mult: 1.25 },
      { afterSeconds: 20, mult: 1.5 },
      { afterSeconds: 30, mult: 2.0 },
      { afterSeconds: 45, mult: 3.0 },
    ] as const,
    extendAdSeconds: 30,
    comboPerKill: 0.08,
    comboMax: 3.5,
    comboDecayPerSec: 0.8,
    comboGraceSec: 2.2,
    draftTimeScale: 0.1,
    draftAutoPickSec: 8,
  },
  player: {
    baseSpeed: 260,
    speedPerLevel: 18,
    accel: 17,
    baseHP: 105,
    hpPerGenLevel: 3,
    dashCooldown: 1.15,
    dashForce: 760,
    dashDuration: 0.18,
    dashInvuln: 0.18,
    invulnAfterHit: 0.18,
    worldBounds: { minX: -800, maxX: 800, minY: -560, maxY: 560 },
  },
  weapon: {
    baseFireCooldown: 0.105,
    laserFireCooldown: 0.06,
    laserTargets: 2,
    baseRange: 365,
    rangePerDamage: 8,
    baseDamage: 11,
    damagePerLevel: 4,
  },
  enemies: {
    maxOnScreen: 32,
    spawnCooldownStart: 0.95,
    spawnCooldownEnd: 0.24,
    spawnDistance: 720,
    weights: {
      grunt: 0.48,
      swarmer: 0.20,
      shooter: 0.16,
      tank: 0.12,
      elite: 0.04,
    },
    scaling: { hpMult: 1.0, hpMultPerRaidSecond: 1 / 75 },
  },
  economy: {
    upgrades: {
      gen:    { base: 25, scale: 1.50 },
      drone:  { base: 60, scale: 1.62 },
      speed:  { base: 45, scale: 1.55 },
      magnet: { base: 50, scale: 1.55 },
      damage: { base: 55, scale: 1.60 },
      luck:   { base: 80, scale: 1.70 },
    },
    coreChanceBase: 0.11,
    coreChancePerLuck: 0.035,
    coreChanceTankBonus: 0.15,
    offlineCapHours: 8,
    spm: { base: 14, drone: 0.22 },
    dailyReward: 100,
    factoryBoostDuration: 120,
    factoryBoostMult: 2,
    startingScrap: 100,
  },
  infestation: {
    maxMachineRatio: 0.5,
    machinesLostPerFail: { min: 1, max: 3 },
    failsBeforeInfestation: 3,
    killsToRestoreMachine: 30,
  },
  prestige: {
    minGenLevel: 25,
    minCores: 1000,
    cyberCoreBonus: 0.10,
  },
  powerups: {
    firstSpawnSecNormal: 8,
    firstSpawnSecTutorial: 4,
    spawnIntervalMin: 9,
    spawnIntervalMax: 14,
    maxOnField: 10,
    spawnRadius: 280,
  },
  performance: {
    maxParticles: 360,
    maxPopups: 70,
    maxPickups: 220,
    dtClamp: 0.033,
  },
  rendering: {
    width: 1280,
    height: 720,
    backgroundColor: '#000000',
  },
} as const;

export type BalanceConfig = typeof Balance;
