// All player-facing strings. Default English; secondary languages added in Phase 3.
// Keep this thin during Milestone 0 - additional keys are added as UI is built.

export const Strings = {
  bootOk: 'Boot OK',
  gameTitle: 'NEON FACTORY RAID',
  fps: 'FPS',
  comboLabel: 'COMBO',
  timerLabel: 'TIME',
  extractionOpened: 'EXTRACTION OPEN',
  extractionHold: 'HOLD',
  summaryExtracted: 'EXTRACTION COMPLETE',
  summaryFailed: 'RAID FAILED',
  summaryCollapsed: 'TIME COLLAPSED',
  summaryScrap: 'SCRAP',
  summaryCores: 'CORES',
  summaryFactory: 'FACTORY',
  summaryRedeploy: 'ONE MORE RAID',
  summaryDoubleLoot: 'DOUBLE LOOT  [M20]',
  summaryPenalty: '-50% UNBANKED LOOT',
  greedLabel: 'GREED',
  hpLabel: 'HP',
  factoryStubTitle: 'FACTORY',
  factoryStubSub: 'Factory hub — Milestone 8',
  factoryDeploy: 'DEPLOY',
  factorySpm: 'SPM',
  factoryDeployHint: 'STAND ON PAD TO DEPLOY',
  // FTUE captions per blueprint §5.2 - max 4 words each.
  ftueMove: 'MOVE',
  ftueDash: 'DASH',
  ftuePowerup: 'POWER UP!',
  ftueExtract: 'EXTRACT',
  ftueTutorialBanner: 'TUTORIAL',
  ftueDeployPrompt: 'DEPLOY',
  // Tutorial summary single-button label per §5.2 ("Single button: UPGRADE").
  summaryUpgrade: 'UPGRADE',

  // M15 — in-run drafting modal.
  draftTitle: 'CHOOSE SIGNAL MOD',
  draftRarityCommon: 'COMMON',
  draftRarityRare: 'RARE',
  draftRarityEpic: 'EPIC',

  // M15 — card names + one-line effects per §12.2.
  // Implemented:
  cardSharperShotsName: 'Sharper Shots',
  cardSharperShotsEffect: '+15% damage',
  cardQuickFeetName: 'Quick Feet',
  cardQuickFeetEffect: '+10% movement speed',
  cardWideMagnetName: 'Wide Magnet',
  cardWideMagnetEffect: '+20% pickup range',
  cardHardyName: 'Hardy',
  cardHardyEffect: '+20 max HP',
  cardBurstFireName: 'Burst Fire',
  cardBurstFireEffect: '+10% fire rate',
  cardLuckyName: 'Lucky',
  cardLuckyEffect: '+5% core drop chance',
  cardPierceName: 'Pierce',
  cardPierceEffect: 'Shots pierce 1 enemy',
  cardChainLightningName: 'Chain Lightning',
  cardChainLightningEffect: 'Shots chain to nearest enemy',
  cardMagnetStormName: 'Magnet Storm',
  cardMagnetStormEffect: 'Pickups rush to you for 8s',
  cardDashMasterName: 'Dash Master',
  cardDashMasterEffect: '-30% dash cooldown',
  cardHealOnPickupName: 'Heal on Pickup',
  cardHealOnPickupEffect: 'Scrap restores 1 HP',
  cardCritShotName: 'Crit Shot',
  cardCritShotEffect: '15% chance for 3x damage',
  cardOrbitalShieldName: 'Orbital Shield',
  cardOrbitalShieldEffect: 'Shield bubble, regens every 12s',
  cardSplitShotName: 'Split Shot',
  cardSplitShotEffect: 'Shots fork into 2',
  cardDroneMultiplierName: 'Drone Multiplier',
  cardDroneMultiplierEffect: 'Drone count doubled',
  cardVampiricName: 'Vampiric',
  cardVampiricEffect: '10% kills heal 5 HP',
  cardGreedSurgeName: 'Greed Surge',
  cardGreedSurgeEffect: '+50% loot multiplier',
  cardPhoenixName: 'Phoenix',
  cardPhoenixEffect: 'Revive once at 50% HP',

  // M15 — deferred cards (still listed so the pool count is honest, but
  // filtered out at draw time). See CardDefs.ts.
  cardRicochetName: 'Ricochet',
  cardRicochetEffect: 'Shots bounce off walls',
  cardSlowFieldName: 'Slow Field',
  cardSlowFieldEffect: 'Enemies near you slow 30%',
  cardFrenzyModeName: 'Frenzy Mode',
  cardFrenzyModeEffect: '-50% fire rate at low HP',
  cardNovaDashName: 'Nova Dash',
  cardNovaDashEffect: 'Dash creates damaging ring',
  cardTimeDilationName: 'Time Dilation',
  cardTimeDilationEffect: 'Enemies move 15% slower',
  cardPyrokineticName: 'Pyrokinetic',
  cardPyrokineticEffect: 'Death blasts harm nearby',

  draftAutoPick: 'Auto-pick in',
  draftPicked: 'PICKED',

  // M16 — operator metadata + picker UI.
  operatorPanelTitle: 'OPERATORS',
  operatorPulseName: 'PULSE',
  operatorPulseDesc: 'Balanced kit',
  operatorVantaName: 'VANTA',
  operatorVantaDesc: '+2 drones, -10% damage',
  operatorSurgeName: 'SURGE',
  operatorSurgeDesc: '+50% damage, -25% HP',
  operatorLodestoneName: 'LODESTONE',
  operatorLodestoneDesc: '+100% magnet, slow',
  operatorLocked: 'LOCKED',
  operatorComingSoon: 'COMING SOON',
  operatorCostPrefix: 'Costs ',
  operatorCostSuffix: ' Cores',
  operatorSelected: 'SELECTED',
  operatorUnlock: 'UNLOCK',
} as const;

export type StringKey = keyof typeof Strings;
